version: "3.3"

services:
  proxy:
    image: traefik:v2.4
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    env_file:
      - .env
    command:
      - --providers.docker
      - --providers.docker.exposedByDefault=false
      - --log
      - --accesslog
      - --api.insecure=false
      - --entryPoints.http.address=:80
      - --entryPoints.http.http.redirections.entryPoint.to=https
      - --entryPoints.http.http.redirections.entryPoint.scheme=https
      - --entryPoints.https.address=:443
      - --entryPoints.https.http.tls.certResolver=letsencrypt
      - --certificatesresolvers.letsencrypt.acme.email=${EMAIL?Variable not set}
      - --certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json
      - --certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=http
    labels:
      - traefik.enable=true
      - traefik.http.middlewares.base-auth.basicauth.users=test:$$2y$$05$$UpXgjgU2w4NR8eQSiYZEZ.RWuN4qJEkLY1YoyqymSNaLPC.h9kkWe  # passwd - test
      - traefik.http.routers.dashboard.rule=Host(`monitor.${DOMAIN?Variable not set}`)
      - traefik.http.routers.dashboard.service=api@internal
      - traefik.http.routers.dashboard.middlewares=base-auth
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./volumes/letsencrypt:/letsencrypt

  service1:
    image: etetin/fastami:latest
    labels:
      - traefik.enable=true
      - traefik.http.routers.service1-http.rule=Host(`${DOMAIN?Variable not set}`) && PathPrefix(`/`)

  service2:
    image: etetin/fastami:latest
    expose:
      - 82
    environment:
      - PORT=82
    labels:
      - traefik.enable=true
      - traefik.http.routers.service2-http.rule=Host(`ddd.${DOMAIN?Variable not set}`) && PathPrefix(`/`)
      - traefik.http.services.someshit.loadbalancer.server.port=82
